export const peso = (v) =>
  '₱' + Math.abs(v).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

export const buildPrintHtml = (r, position) => {
  const p = peso
  const rows = r.earnings.map(e =>
    `<div class="row"><span class="label">${e.label}</span><span class="amount">${p(e.amount)}</span></div>`
  ).join('')
  const dRows = r.deductions.map(d =>
    `<div class="row deduction"><span class="label">− ${d.label}</span><span class="amount">${p(d.amount)}</span></div>`
  ).join('')
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Payslip - ${r.employeeName}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:system-ui,-apple-system,sans-serif;background:#fff;color:#2c3e50;font-size:14px;padding:20px}
.payslip{max-width:800px;margin:0 auto;padding:40px;border:2px solid #2c3e50}
.header{text-align:center;border-bottom:3px solid #2c3e50;padding-bottom:20px;margin-bottom:30px}
.header h1{font-size:28px;color:#2c3e50;margin-bottom:5px}
.header p{color:#7f8c8d;font-size:16px}
.info{display:flex;justify-content:space-between;margin-bottom:30px;padding:20px;background:#f8f9fa;border-radius:8px}
.info div{flex:1}
.info h3{font-size:12px;text-transform:uppercase;color:#7f8c8d;margin-bottom:5px}
.info p{font-size:18px;font-weight:600;color:#2c3e50}
.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-bottom:25px}
.m-box{background:#f8f9fa;padding:15px;border-radius:8px;text-align:center}
.m-box .v{font-size:20px;font-weight:600;color:#2c3e50}
.m-box .l{font-size:12px;color:#7f8c8d;margin-top:5px}
.section{margin-bottom:25px}
.section-title{font-size:16px;font-weight:600;color:#2c3e50;border-bottom:2px solid #3498db;padding-bottom:8px;margin-bottom:15px}
.row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #ecf0f1}
.row:last-child{border-bottom:none}
.label{color:#555}
.amount{font-weight:600;color:#2c3e50}
.deduction .label,.deduction .amount{color:#e74c3c}
.total{display:flex;justify-content:space-between;padding:15px 20px;margin-top:10px;background:#2c3e50;color:#fff;font-size:18px;font-weight:600;border-radius:8px}
.net{background:#27ae60}
.foot{text-align:center;margin-top:40px;padding-top:20px;border-top:1px solid #ecf0f1;color:#95a5a6;font-size:12px}
@media print{body{padding:0}.payslip{border:none}button{display:none}}
</style></head>
<body><div class="payslip">
<div class="header"><h1>PAYSLIP</h1><p>Philippine Payroll System</p></div>
<div class="info">
<div><h3>Employee Name</h3><p>${r.employeeName}</p></div>
<div><h3>Position</h3><p>${position || '—'}</p></div>
<div><h3>Pay Period</h3><p>Period ${r.period}</p></div>
</div>
<div class="metrics">
<div class="m-box"><div class="v">${p(r.hourlyRate)}/hr</div><div class="l">Hourly Rate</div></div>
<div class="m-box"><div class="v">${r.totalRegHrs} hrs</div><div class="l">Regular Hours</div></div>
<div class="m-box"><div class="v">${r.totalOTHrs} hrs</div><div class="l">OT Hours</div></div>
</div>
<div class="section"><div class="section-title">Earnings</div>${rows}
<div class="total"><span>Gross Pay</span><span>${p(r.grossPay)}</span></div></div>
<div class="section"><div class="section-title">Deductions</div>${dRows || '<div class="row"><span class="label" style="color:#999">None</span><span class="amount">—</span></div>'}
<div class="total"><span>Total Deductions</span><span>${p(r.totalDeductions)}</span></div></div>
<div class="total net"><span>Net Pay</span><span>${p(r.netPay)}</span></div>
<div class="foot"><p>Generated by PaySlip PH</p></div>
</div></body></html>`
}
